#ecoding = utf-8

import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    #自定义用例执行顺序
    # suite = unittest.TestSuite()
    # tests = [TestMathFunc("test_add"),TestMathFunc("test_minus"),TestMathFunc("test_divide")]
    # suite.addTests(tests)
    # runner = unittest.TextTestRunner(verbosity =2)
    # runner.run(suite)

    # #将执行结果输出到文件中，不能自定义用例的执行顺序
    # suite = unittest.TestSuite()
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    # with open('UnittestTextReport.txt','a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    #将执行结果输出到HTML页面
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    with open('HTMLTestRunner','wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestReport',
                                verbosity=2
                                )
        runner.run(suite)